export const route = {
  HOME: "/",
  SEARCH: "search",
  AUTH: "auth",
  LOGIN: "login",
  OTP: "otp",
  REGISTER: "register",
  TWEET: "/tweet",
  PROFILE: "profile",
  NOTIFY: "notify",
  NOTIFY_FRIEND: "request-friends",
  MESSENGER: "messenger",
  MESSENGER_INFO: "info",
  TWEET_P: "",
  IMAGE_P: "image",
  SHARE_P: "share",
  FRIEND_P: "friends",
  FLOWER_P: "followers",
};
